services:
  - type: web
    name: whatsapp-business-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: DOMAIN_URL
        sync: false
      - key: WHATSAPP_APP_ID
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_SYSTEM_USER_ID
        sync: false
      - key: WHATSAPP_SYSTEM_USER_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
